apiVersion: konstruct.io/v1alpha1
kind: ComponentMetadata
metadata:
  name: workload-cluster
  description: "Workload cluster configuration"
spec:
  version: "v1.0.0"
  dependencies: []
  templates:
    - name: "mobile-team.yaml"
      description: "Mobile team workload cluster configuration"
  inputs:
    - name: clusterName
      type: string
      description: "Name of the workload cluster"
      required: true
    - name: cloudProvider
      type: string
      description: "Cloud provider for the cluster"
      enum: ["aws", "gcp", "azure", "civo"]
      required: true
    - name: region
      type: string
      description: "Cloud provider region"
      required: true
    - name: nodeCount
      type: integer
      description: "Number of worker nodes"
      default: 3
      validation:
        min: 1
        max: 100