apiVersion: v2
name: workload-downstream-cluster
description: A Helm chart for provisioning downstream workload clusters with infrastructure and core services
type: application
version: 0.1.0
appVersion: "1.0"
