apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: {{ .Values.workloadClusterName }}-infrastructure
spec:
  providerConfigRef: 
    name: {{ .Values.workloadClusterName }}
  forProvider:
    source: Remote
    module: {{ .Values.workloadClusterTerraformModuleUrl }}
    vars:
    - key: cluster_name
      value: "{{ .Values.workloadClusterName }}"
    - key: cluster_region
      value: "{{ .Values.workloadClusterRegion }}"
    - key: node_count
      value: "{{ .Values.workloadNodeCount }}"
    - key: node_type
      value: "{{ .Values.workloadNodeType }}"
    - key: ami_type
      value: "{{ .Values.workloadAmiType }}"


